server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/public/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  resources:
    static-locations: classpath:/templates/
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#    timeout: 0
mybatis:
  mapper-locations: classpath:cn/lifecycle/mapper/*.xml
logging:
  path: d:/tools



